set basejump_stl_dir          $::env(BASEJUMP_STL_DIR)
set bsg_manycore_dir          $::env(BSG_MANYCORE_DIR)
set bsg_designs_target_dir    $::env(BSG_DESIGNS_TARGET_DIR)
set bsg_packaging_dir         $::env(BSG_PACKAGING_DIR)

set SVERILOG_PACKAGE_FILES [join "
  $basejump_stl_dir/bsg_misc/bsg_defines.v
  $basejump_stl_dir/bsg_tag/bsg_tag_pkg.v
  $basejump_stl_dir/bsg_cache/bsg_cache_pkg.v
  $basejump_stl_dir/bsg_noc/bsg_noc_pkg.v
  $basejump_stl_dir/bsg_noc/bsg_mesh_router_pkg.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_router_pkg.v
  $bsg_manycore_dir/v/bsg_manycore_pkg.v
  $bsg_manycore_dir/v/bsg_manycore_addr_pkg.v
  $bsg_manycore_dir/v/vanilla_bean/bsg_vanilla_pkg.v
  $bsg_manycore_dir/imports/HardFloat/source/bsg_hardfloat_pkg.v
"]

set SVERILOG_SOURCE_FILES [join "
  $SVERILOG_PACKAGE_FILES
  $bsg_designs_target_dir/v/bsg_manycore_tile_compute_ruche_wrapper.v
  $basejump_stl_dir/bsg_misc/bsg_counter_clear_up.v
  $basejump_stl_dir/bsg_misc/bsg_counter_up_down_variable.v
  $basejump_stl_dir/bsg_misc/bsg_counter_up_down.v
  $basejump_stl_dir/bsg_misc/bsg_counter_set_down.v
  $basejump_stl_dir/bsg_misc/bsg_mux2_gatestack.v
  $basejump_stl_dir/bsg_misc/bsg_mux.v
  $basejump_stl_dir/bsg_misc/bsg_mux_bitwise.v
  $basejump_stl_dir/bsg_misc/bsg_dff.v
  $basejump_stl_dir/bsg_misc/bsg_dff_en.v
  $basejump_stl_dir/bsg_misc/bsg_dff_en_bypass.v
  $basejump_stl_dir/bsg_misc/bsg_dff_reset_en_bypass.v
  $basejump_stl_dir/bsg_misc/bsg_dff_reset.v
  $basejump_stl_dir/bsg_misc/bsg_dff_reset_en.v
  $basejump_stl_dir/bsg_misc/bsg_dff_reset_set_clear.v
  $basejump_stl_dir/bsg_misc/bsg_dff_chain.v
  $basejump_stl_dir/bsg_misc/bsg_counter_clock_downsample.v
  $basejump_stl_dir/bsg_misc/bsg_strobe.v
  $basejump_stl_dir/bsg_misc/bsg_buf.v
  $basejump_stl_dir/bsg_misc/bsg_reduce.v
  $basejump_stl_dir/bsg_misc/bsg_xnor.v
  $basejump_stl_dir/bsg_misc/bsg_nand.v
  $basejump_stl_dir/bsg_misc/bsg_nor3.v
  $basejump_stl_dir/bsg_misc/bsg_nor2.v
  $basejump_stl_dir/bsg_misc/bsg_adder_cin.v
  $basejump_stl_dir/bsg_misc/bsg_muxi2_gatestack.v
  $basejump_stl_dir/bsg_misc/bsg_decode_with_v.v
  $basejump_stl_dir/bsg_misc/bsg_decode.v
  $basejump_stl_dir/bsg_misc/bsg_circular_ptr.v
  $basejump_stl_dir/bsg_misc/bsg_priority_encode.v
  $basejump_stl_dir/bsg_misc/bsg_priority_encode_one_hot_out.v
  $basejump_stl_dir/bsg_misc/bsg_encode_one_hot.v
  $basejump_stl_dir/bsg_misc/bsg_expand_bitmask.v
  $basejump_stl_dir/bsg_misc/bsg_mux_segmented.v
  $basejump_stl_dir/bsg_misc/bsg_mux_one_hot.v
  $basejump_stl_dir/bsg_misc/bsg_lru_pseudo_tree_backup.v
  $basejump_stl_dir/bsg_misc/bsg_lru_pseudo_tree_encode.v
  $basejump_stl_dir/bsg_misc/bsg_lru_pseudo_tree_decode.v
  $basejump_stl_dir/bsg_misc/bsg_gray_to_binary.v
  $basejump_stl_dir/bsg_misc/bsg_scan.v
  $basejump_stl_dir/bsg_misc/bsg_round_robin_arb.v
  $basejump_stl_dir/bsg_misc/bsg_crossbar_o_by_i.v
  $basejump_stl_dir/bsg_misc/bsg_transpose.v
  $basejump_stl_dir/bsg_misc/bsg_thermometer_count.v
  $basejump_stl_dir/bsg_misc/bsg_imul_iterative.v
  $basejump_stl_dir/bsg_misc/bsg_idiv_iterative.v
  $basejump_stl_dir/bsg_misc/bsg_idiv_iterative_controller.v
  $basejump_stl_dir/bsg_misc/bsg_less_than.v
  $basejump_stl_dir/bsg_misc/bsg_inv.v
  $basejump_stl_dir/bsg_misc/bsg_buf_ctrl.v
  $basejump_stl_dir/bsg_misc/bsg_array_concentrate_static.v
  $basejump_stl_dir/bsg_misc/bsg_concentrate_static.v
  $basejump_stl_dir/bsg_misc/bsg_unconcentrate_static.v
  $basejump_stl_dir/bsg_misc/bsg_arb_round_robin.v

  $basejump_stl_dir/bsg_mem/bsg_mem_1rw_sync.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1rw_sync_synth.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1r1w.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1r1w_synth.v
  $basejump_stl_dir/bsg_mem/bsg_mem_2r1w_sync.v
  $basejump_stl_dir/bsg_mem/bsg_mem_2r1w_sync_synth.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1rw_sync_mask_write_bit_synth.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1rw_sync_mask_write_byte.v
  $basejump_stl_dir/bsg_mem/bsg_mem_1rw_sync_mask_write_byte_synth.v

  $basejump_stl_dir/bsg_dataflow/bsg_channel_tunnel.v
  $basejump_stl_dir/bsg_dataflow/bsg_channel_tunnel_in.v
  $basejump_stl_dir/bsg_dataflow/bsg_channel_tunnel_out.v
  $basejump_stl_dir/bsg_dataflow/bsg_parallel_in_serial_out.v
  $basejump_stl_dir/bsg_dataflow/bsg_serial_in_parallel_out_full.v
  $basejump_stl_dir/bsg_dataflow/bsg_serial_in_parallel_out.v
  $basejump_stl_dir/bsg_dataflow/bsg_two_fifo.v
  $basejump_stl_dir/bsg_dataflow/bsg_one_fifo.v
  $basejump_stl_dir/bsg_dataflow/bsg_round_robin_n_to_1.v
  $basejump_stl_dir/bsg_dataflow/bsg_1_to_n_tagged_fifo.v
  $basejump_stl_dir/bsg_dataflow/bsg_1_to_n_tagged.v
  $basejump_stl_dir/bsg_dataflow/bsg_round_robin_1_to_n.v
  $basejump_stl_dir/bsg_dataflow/bsg_round_robin_2_to_2.v
  $basejump_stl_dir/bsg_dataflow/bsg_fifo_1r1w_small.v
  $basejump_stl_dir/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v
  $basejump_stl_dir/bsg_dataflow/bsg_make_2D_array.v
  $basejump_stl_dir/bsg_dataflow/bsg_flatten_2D_array.v
  $basejump_stl_dir/bsg_dataflow/bsg_fifo_tracker.v
  $basejump_stl_dir/bsg_dataflow/bsg_fifo_1r1w_pseudo_large.v
  $basejump_stl_dir/bsg_dataflow/bsg_fifo_1rw_large.v
  $basejump_stl_dir/bsg_dataflow/bsg_fifo_1r1w_large.v

  $basejump_stl_dir/bsg_async/bsg_sync_sync.v
  $basejump_stl_dir/bsg_async/bsg_launch_sync_sync.v
  $basejump_stl_dir/bsg_async/bsg_async_fifo.v
  $basejump_stl_dir/bsg_async/bsg_async_ptr_gray.v
  $basejump_stl_dir/bsg_async/bsg_async_credit_counter.v

  $basejump_stl_dir/bsg_noc/bsg_mesh_stitch.v
  $basejump_stl_dir/bsg_noc/bsg_ready_and_link_async_to_wormhole.v
  $basejump_stl_dir/bsg_noc/bsg_noc_repeater_node.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_router.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_router_decoder_dor.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_router_input_control.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_router_output_control.v
  $basejump_stl_dir/bsg_noc/bsg_mesh_router_buffered.v
  $basejump_stl_dir/bsg_noc/bsg_mesh_router.v
  $basejump_stl_dir/bsg_noc/bsg_mesh_router_decoder_dor.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_concentrator.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_concentrator_in.v
  $basejump_stl_dir/bsg_noc/bsg_wormhole_concentrator_out.v

  $basejump_stl_dir/bsg_tag/bsg_tag_client_unsync.v
  $basejump_stl_dir/bsg_tag/bsg_tag_client.v
  $basejump_stl_dir/bsg_tag/bsg_tag_master.v

  $basejump_stl_dir/bsg_cache/bsg_cache.v
  $basejump_stl_dir/bsg_cache/bsg_cache_decode.v
  $basejump_stl_dir/bsg_cache/bsg_cache_dma.v
  $basejump_stl_dir/bsg_cache/bsg_cache_miss.v
  $basejump_stl_dir/bsg_cache/bsg_cache_sbuf.v
  $basejump_stl_dir/bsg_cache/bsg_cache_sbuf_queue.v

  $bsg_manycore_dir/imports/HardFloat/source/compareRecFN.v
  $bsg_manycore_dir/imports/HardFloat/source/divSqrtRecFN_small.v
  $bsg_manycore_dir/imports/HardFloat/source/fNToRecFN.v
  $bsg_manycore_dir/imports/HardFloat/source/HardFloat_primitives.v
  $bsg_manycore_dir/imports/HardFloat/source/HardFloat_rawFN.v
  $bsg_manycore_dir/imports/HardFloat/source/iNToRecFN.v
  $bsg_manycore_dir/imports/HardFloat/source/isSigNaNRecFN.v
  $bsg_manycore_dir/imports/HardFloat/source/mulAddRecFN.v
  $bsg_manycore_dir/imports/HardFloat/source/recFNToFN.v
  $bsg_manycore_dir/imports/HardFloat/source/recFNToIN.v
  $bsg_manycore_dir/imports/HardFloat/source/RISCV/HardFloat_specialize.v

  $bsg_manycore_dir/v/bsg_manycore_pod_ruche.v
  $bsg_manycore_dir/v/bsg_manycore_tile_vcache_array.v
  $bsg_manycore_dir/v/bsg_manycore_tile_vcache.v
  $bsg_manycore_dir/v/bsg_cache_dma_to_wormhole.v
  $bsg_manycore_dir/v/bsg_manycore_tile_compute_array_ruche.v
  $bsg_manycore_dir/v/bsg_manycore_endpoint.v
  $bsg_manycore_dir/v/bsg_manycore_endpoint_standard.v
  $bsg_manycore_dir/v/bsg_manycore_reg_id_decode.v
  $bsg_manycore_dir/v/bsg_manycore_link_async_to_wormhole.v
  $bsg_manycore_dir/v/bsg_manycore_vcache_blocking.v
  $bsg_manycore_dir/v/bsg_manycore_link_to_cache.v
  $bsg_manycore_dir/v/bsg_manycore_link_sif_tieoff.v
  $bsg_manycore_dir/v/bsg_manycore_ruche_x_link_sif_tieoff.v
  $bsg_manycore_dir/v/bsg_manycore_tile_compute_ruche.v
  $bsg_manycore_dir/v/bsg_manycore_mesh_node.v
  $bsg_manycore_dir/v/bsg_manycore_hetero_socket.v
  $bsg_manycore_dir/v/bsg_manycore_eva_to_npa.v
  $bsg_manycore_dir/v/bsg_manycore_dram_hash_function.v
  $bsg_manycore_dir/v/bsg_manycore_lock_ctrl.v
  $bsg_manycore_dir/v/bsg_1hold.v
  $bsg_manycore_dir/v/bsg_ruche_buffer.v
  $bsg_manycore_dir/v/vanilla_bean/bsg_manycore_proc_vanilla.v
  $bsg_manycore_dir/v/vanilla_bean/network_rx.v
  $bsg_manycore_dir/v/vanilla_bean/network_tx.v
  $bsg_manycore_dir/v/vanilla_bean/vanilla_core.v
  $bsg_manycore_dir/v/vanilla_bean/load_packer.v
  $bsg_manycore_dir/v/vanilla_bean/icache.v
  $bsg_manycore_dir/v/vanilla_bean/cl_decode.v
  $bsg_manycore_dir/v/vanilla_bean/regfile.v
  $bsg_manycore_dir/v/vanilla_bean/regfile_synth.v
  $bsg_manycore_dir/v/vanilla_bean/scoreboard.v
  $bsg_manycore_dir/v/vanilla_bean/alu.v
  $bsg_manycore_dir/v/vanilla_bean/idiv.v
  $bsg_manycore_dir/v/vanilla_bean/lsu.v
  $bsg_manycore_dir/v/vanilla_bean/fcsr.v
  $bsg_manycore_dir/v/vanilla_bean/mcsr.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_int.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_float.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_float_aux.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_int_fclass.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_fmin_fmax.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_fdiv_fsqrt.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_float_fma.v
  $bsg_manycore_dir/v/vanilla_bean/fpu_float_fma_round.v
"]

#  $basejump_stl_dir/bsg_clk_gen/bsg_dly_line.v

